### ISSUE TITLE
Add option for Sambamba tmp directory

### ISSUE THREAD

**Issue by adbeggs** [nf-core/oncoanalyser#112]
### Description of feature

Hi

I've had multiple crashes on a Slurm based HPC environment as sambamba sort fills up the compute nodes /tmp directory and crashes out. Can you add a command line option to allow pre-specification of this? I have modified my bwamem2/main.nf for now which works

A

**Comment by scwatts** [comment]
Hi @adbeggs, thanks for opening the issue! You should be able to set `ext.args3` as needed for the `BWAMEM2_ALIGN` process to achieve the desired behaviour, which is applied here:

https://github.com/nf-core/oncoanalyser/blob/4227bc1083209d79c8735d32e6c75f762a640006/modules/local/bwa-mem2/mem/main.nf#L51-L55

In terms of hardcoding `--tmpdir ./` for the `sambamba sort` command, there doesn't seem to be an obvious answer since doing this is optimal for certain environments (e.g. HPC with high-bandwidth, low-latency interconnect) but less so for some cloud compute setups (e.g. AWS with FusionFS where r/w to S3 should be minimised).
