### ISSUE TITLE
Error when using bam files without 'chr' 

### ISSUE THREAD

**Issue by PaulaOteroS** [nf-core/oncoanalyser#30]
### Description of the bug

Hi, I'm a new user and I've tried the pipeline using bam files from a tumor-normal pair with the notation for chromosomes not including the 'chr' particle. After running it, I got results from Virusbreakend, flagstats and bamtools metrics, but all the other tasks failed. I am wondering if this could be due to the bams notation (I saw intermediate files use 'chr') and if there is a way to solve it apart from changing the bam files. Thanks!

### Command used and terminal output

```console
nextflow run nf-core/oncoanalyser \
  -r 0.4.5 \
  -c ${CONFIG} \
  --input ${INPUT} \
  --mode wgts \
  --genome GRCh38_hmf  \
  --ref_data_virusbreakenddb_path ${VIRUS_PATH} \
  --ref_data_hmf_data_path ${HMF_DATA_PATH}/5.34_38--2 \
  --outdir ${OUTDIR} \
  -resume \
  -profile singularity
```

### System information

nextflow/23.04.2
Hardware: HPC
Executor: slurm and local
Container engine: Singularity
Version of nf-core/oncoanalyser: 0.4.5

**Comment by scwatts** [comment]
Hi @PaulaOteroS, thanks for the question. If you're using a custom GRCh38 reference, the contig names must be prefixed with 'chr'. More generally it is strongly recommended to use the Hartwig-distributed reference genomes rather than a custom one.

If you can tell me more about your data and whether it's feasible for you to run oncoanalyser analyses from FASTQ, I can provide some further suggestions.

**Comment by scwatts** [comment]
Closing this issue for now, please reopen if needed
